config/routes.rb
Anotar::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }

  get 'notes/all' => 'notes#all', :as => :notes_all
  get 'notes/favs' => 'notes#favs', :as => :notes_favorited
  get 'notes/shared' => 'notes#shared', :as => :notes_shared
  get 'hashtags/nav' => 'hashtags#show'
  get 'hashtags/:name' => 'hashtags#show', :as => :hashtag
  get 'hashtags' => 'hashtags#index', :as => :hashtags
  get 'admins/console' => 'admins#index', :as => :admins_console
  get 'admins/user/:id' => 'admins#show', :as => :admins_user

  resources :notes

  authenticated :user do
    root :to => 'notes#index'
  end
  root :to => 'notes#index'

end

app/views/admins/index.html.haml
- content_for :head do
  = javascript_include_tag 'http://www.google.com/jsapi'

%ul.nav.nav-tabs
  %li.active= link_to 'Overview', '#overview', :'data-toggle' => "tab"
  %li= link_to 'Users', '#users', :'data-toggle' => "tab"
  %li= link_to 'Sessions', '#sessions', :'data-toggle' => "tab"
  %li= link_to 'Registers', '#registers', :'data-toggle' => "tab"
  %li= link_to 'Logins', '#logins', :'data-toggle' => "tab"
  %li= link_to 'Hashtags', '#hashtags', :'data-toggle' => "tab"

.tab-content
  .tab-pane.active#overview
    .thumbnails
      %li.span8
        .thumbnail
          %h4 Users distribution
          #users_chart{:style => "width: 400px; height: 240px;"}
          = render_chart @users_chart, 'users_chart'
      %li.span4
        .thumbnail
          %h4 Numbers
          %h5 Total users: #{@users.size + @sessions.size}
          %h5 Total notes: #{@notes_count}
          %h5 Total hashtags: #{@hashtags.size}
  .tab-pane#users
    .thumbnails
      %li.span12
        .thumbnail
          %table.table.table-hover.table-condensed
            %thead
              %tr
                %th user
                %th email
                %th created at
                %th last sign
                %th sign_in
                %th confirmed
                %th notes
            %tbody
              - @users.each do |user|
                - if user.admin
                  %tr.info
                    %td= link_to user.username, admins_user_path(user.author_id)
                    %td= link_to user.email, "mailto:#{user.email}"
                    %td= user.created_at
                    %td= user.last_sign_in_at
                    %td= user.sign_in_count
                    %td= user.confirmed_at
                    %td= user.notes.size
                - elsif user.confirmed_at
                  %tr.success
                    %td= link_to user.username, admins_user_path(user.author_id)
                    %td= link_to user.email, "mailto:#{user.email}"
                    %td= user.created_at
                    %td= user.last_sign_in_at
                    %td= user.sign_in_count
                    %td= user.confirmed_at
                    %td= user.notes.size
                - else
                  %tr
                    %td= link_to user.username, admins_user_path(user.author_id)
                    %td= link_to user.email, "mailto:#{user.email}"
                    %td= user.created_at
                    %td= user.last_sign_in_at
                    %td= user.sign_in_count
                    %td= user.confirmed_at
                    %td= user.notes.size
  .tab-pane#sessions
    .thumbnails
      %li.span12
        .thumbnail
          %table.table.table-hover.table-condensed
            %thead
              %tr
                %th session_id
                %th author_id
                %th created at
                %th updated at
                %th visits
                %th notes
            %tbody
              - @sessions.each do |user|
                %tr
                  %td= user.session_id
                  %td= link_to user.author_id, admins_user_path(user.author_id)
                  %td= user.created_at
                  %td= user.updated_at
                  %td= user.visits
                  %td= @session_notes_count[user.session_id]
  .tab-pane#registers
    .thumbnails
      %li.span12
        .thumbnail
          %h4 User register count: #{@users.size}
          #registers_chart{:style => "width: 650px; height: 240px;"}
          = render_chart @registers_chart, 'registers_chart'
  .tab-pane#logins
    .thumbnails
      %li.span12
        .thumbnail
          %h4 Average user logins: #{@logins_average}
          #logins_chart{:style => "width: 650px; height: 240px;"}
          = render_chart @logins_chart, 'logins_chart'
  .tab-pane#hashtags
    .thumbnails
      %li.span12
        .thumbnail
          %table.table.table-hover.table-condensed
            %thead
              %tr
                %th Hashtag name
                %th Hits count
                %th Created at
                %th Updated at
            %tbody
              - @hashtags.each do |h|
                %tr
                  %td= h.name
                  %td= h.hits
                  %td= h.created_at
                  %td= h.updated_at

app/views/admins/show.html.haml
-# Paginate hidden counters
%input#current_page{:type => 'hidden'}
%input#show_per_page{:type => 'hidden'}
-# Notes list
#content
  - unless @notes.blank?
    - @notes.each do |note|
      .note
        .well{:style => "background-color: #FFFCB6"}
          %h4.note-title
            - note_title = ""
            - if note.fav then note_title << " <i class='icon-star' title='Favorited with @fav@'></i>  " end
            - note_title << note.title
            = raw note_title
          %p.note-text= raw note.html_text
          .note-bottom
            .note-last-edit.pull-left= link_to note.updated_at.in_time_zone("Madrid").strftime("%B %d, %Y at %I:%M %p"), note_path(note)
            .note-delete-button.pull-right= link_to(raw("<i class='icon-trash'></i>"), note_path(note), :method => :delete, :data => { :confirm => 'Do you want to delete the note?' })
            .note-edit-button.pull-right= link_to(raw("<i class='icon-edit'></i>"), edit_note_path(note))
            - if note.shared
              .visible-phone
                %br
                .btn-group.dropup.pull-left
                  %a.btn.btn-link.btn-block.dropdown-toggle{:'data-toggle' => "dropdown", :href => "#"}
                    %i.icon-globe
                    Public link
                  %ul.dropdown-menu
                    %li
                      %ul.nav.nav-list
                        %li.nav-header Note shared at
                        %li
                          = raw ("<i class='icon-globe'></i> <i>http://www.anotar.me" + note_path(note) + "</i>")
              .hidden-phone
                .shared-link.pull-right{:title => "Shared with @public@"}= raw ("<i class='icon-globe'></i> at <i>http://www.anotar.me" + note_path(note) + "</i>")
- unless @notes.blank? || @notes.size <= 5
  .pagination.pagination-centered#page_navigation